# Generated by Django 5.0.1 on 2024-02-05 11:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "slug",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("start_timestamp", models.BigIntegerField()),
                ("end_timestamp", models.BigIntegerField()),
                ("user_email", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=255)),
                ("reminded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
